# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ds=app.settings.test --reuse-db --create-db --import-mode=importlib"
python_files = [
    "tests.py",
    "test_*.py",
]

# ==== Coverage ====
[tool.coverage.run]
include = ["app/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]